/**
 * Alert sounds. Plays `public/sounds/alert.wav` / `alert-critical.wav`
 * (tiny CC0 tones generated by e2e/make_sounds.mjs). Falls back to a
 * WebAudio beep when the file cannot be played. `unlockAudio()` is called
 * on the login click so the first play is allowed by autoplay policies.
 */

let unlocked = false;
let ctx: AudioContext | null = null;

function getCtx(): AudioContext | null {
  try {
    if (!ctx) ctx = new (window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext)();
    return ctx;
  } catch {
    return null;
  }
}

export function unlockAudio(): void {
  const c = getCtx();
  if (c && c.state === 'suspended') void c.resume();
  unlocked = true;
}

function beep(critical: boolean): void {
  const c = getCtx();
  if (!c) return;
  const osc = c.createOscillator();
  const gain = c.createGain();
  osc.type = 'sine';
  osc.frequency.value = critical ? 1046 : 784;
  gain.gain.value = 0.0001;
  osc.connect(gain);
  gain.connect(c.destination);
  const t = c.currentTime;
  gain.gain.exponentialRampToValueAtTime(0.25, t + 0.02);
  gain.gain.exponentialRampToValueAtTime(0.0001, t + (critical ? 0.6 : 0.35));
  osc.start(t);
  osc.stop(t + (critical ? 0.65 : 0.4));
  if (critical) {
    const osc2 = c.createOscillator();
    const g2 = c.createGain();
    osc2.frequency.value = 1318;
    g2.gain.value = 0.0001;
    osc2.connect(g2);
    g2.connect(c.destination);
    g2.gain.exponentialRampToValueAtTime(0.25, t + 0.32);
    g2.gain.exponentialRampToValueAtTime(0.0001, t + 0.9);
    osc2.start(t + 0.3);
    osc2.stop(t + 0.95);
  }
}

export function playAlertSound(critical = false): void {
  const file = critical ? '/sounds/alert-critical.wav' : '/sounds/alert.wav';
  try {
    const audio = new Audio(file);
    audio.volume = 0.7;
    const p = audio.play();
    if (p && typeof p.catch === 'function') p.catch(() => beep(critical));
  } catch {
    beep(critical);
  }
  if (!unlocked) unlocked = true;
}
